import { PRODUCT_STATUS, PRODUCT_TYPE, PRICING_MODEL } from "./productConstants.js";

export const PRODUCTS = Object.freeze([
  {
    productId: "PRD-000001",
    sku: "AI-AGENT-ENT",
    name: "AI Agent Enterprise",
    displayName: "企業 AI Agent 導入",
    businessUnitCode: "AI_PLATFORM",
    type: PRODUCT_TYPE.PROJECT,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依需求、流程數量、串接系統與維護範圍估價。",
    description: "企業內部 AI Agent、CRM 自動化、資料整理、Email 草稿、Calendar / Telegram 通知與工作流程自動化。",
    targetCustomers: ["中小企業", "業務團隊", "物流公司", "製造業"],
    keywords: ["AI Agent", "AI", "CRM", "自動化", "流程", "Email", "Calendar", "Telegram"],
    deliverables: ["需求訪談", "流程設計", "AI Prompt", "系統串接", "測試驗收", "教育訓練"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000002",
    sku: "AI-CONSULT",
    name: "AI Consulting",
    displayName: "AI 顧問導入規劃",
    businessUnitCode: "AI_PLATFORM",
    type: PRODUCT_TYPE.SERVICE,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依顧問時數與文件交付範圍估價。",
    description: "協助企業盤點流程、規劃 AI 導入路線、建立 PoC 與導入評估。",
    targetCustomers: ["企業主管", "數位轉型團隊", "業務單位"],
    keywords: ["AI顧問", "導入", "PoC", "流程盤點", "數位轉型"],
    deliverables: ["現況盤點", "導入藍圖", "PoC 規劃", "風險評估"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000101",
    sku: "AOI-SW-CUSTOM",
    name: "AOI Vision Inspection Software",
    displayName: "AOI 視覺檢測軟體",
    businessUnitCode: "AOI_SOFTWARE",
    type: PRODUCT_TYPE.SOFTWARE,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依檢測項目、相機數量、判定規則、資料匯出需求估價。",
    description: "SN 掃碼、自動拍照、OK/NG 判定、Excel 紀錄、防呆機制與客製化影像檢測流程。",
    targetCustomers: ["科技廠", "重工檢測", "電子製造業", "品質部門"],
    keywords: ["AOI", "視覺檢測", "影像", "OK/NG", "SN", "條碼", "Excel", "重工"],
    deliverables: ["檢測流程設計", "軟體開發", "相機串接", "Excel 匯出", "現場測試"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000102",
    sku: "AOI-DATA-REC",
    name: "AOI Data Record Module",
    displayName: "AOI 自動紀錄數據模組",
    businessUnitCode: "AOI_SOFTWARE",
    type: PRODUCT_TYPE.SOFTWARE,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依欄位、Excel 格式、資料來源與防呆規則估價。",
    description: "掃碼按測試，測試完成自動輸入 Excel，降低人工輸入錯誤。",
    targetCustomers: ["品保部門", "測試站", "產線主管"],
    keywords: ["Excel", "自動紀錄", "掃碼", "測試數據", "防呆", "資料"],
    deliverables: ["欄位設計", "Excel 模板", "自動寫入", "錯誤防呆"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000201",
    sku: "3D-PRINT-SVC",
    name: "3D Printing Service",
    displayName: "3D 列印代工",
    businessUnitCode: "PROTOFAB_3D",
    type: PRODUCT_TYPE.SERVICE,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依材料重量、列印時間、失敗風險、後處理與設計複雜度估價。",
    description: "PETG 黑白材料為主，提供 3D 列印代工、小量客製、零件試作與實用品列印。",
    targetCustomers: ["個人客戶", "工作室", "維修單位", "小型工廠"],
    keywords: ["3D列印", "3D 列印", "PETG", "代工", "列印", "Bambu", "P1S"],
    deliverables: ["切片評估", "列印", "品質檢查", "交付"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000202",
    sku: "3D-PEGBOARD",
    name: "Pegboard Accessories",
    displayName: "洞洞板配件",
    businessUnitCode: "PROTOFAB_3D",
    type: PRODUCT_TYPE.PRODUCT,
    pricingModel: PRICING_MODEL.UNIT_PRICE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依尺寸、材料、列印時間與款式估價。",
    description: "26mm 六角洞洞板配件、掛勾、托盤、工具架、筆筒、鑽頭收納等。",
    targetCustomers: ["工具收納需求者", "工作室", "3D 列印客戶"],
    keywords: ["洞洞板", "六角", "掛勾", "托盤", "工具架", "收納", "筆筒", "鑽頭", "3D列印", "3D 列印", "PETG", "配件"],
    deliverables: ["設計檔", "列印件", "尺寸檢查"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000203",
    sku: "3D-LED-FRAME",
    name: "LED Photo Frame",
    displayName: "LED 相框 / 浮雕相框",
    businessUnitCode: "PROTOFAB_3D",
    type: PRODUCT_TYPE.PRODUCT,
    pricingModel: PRICING_MODEL.UNIT_PRICE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依尺寸、LED 結構、列印時間與組裝複雜度估價。",
    description: "浮雕相框、LED 相框、照片展示結構與客製紀念品。",
    targetCustomers: ["個人客戶", "寵物紀念", "救援協會支持者", "禮品需求"],
    keywords: ["LED", "相框", "浮雕", "照片", "客製", "紀念", "寵物"],
    deliverables: ["3D 列印框體", "組裝建議", "成品檢查"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000301",
    sku: "PROC-TAOBAO",
    name: "Taobao / 1688 Procurement",
    displayName: "淘寶 / 1688 工具代購",
    businessUnitCode: "TOOLS_PROCUREMENT",
    type: PRODUCT_TYPE.SERVICE,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "商品成本 + 國際運費 + 報關/集運費 + 服務費。",
    description: "協助找貨、代訂、私人集運、工具與工業品採購。",
    targetCustomers: ["個人買家", "工作室", "工廠", "維修單位"],
    keywords: ["淘寶", "1688", "代購", "工具", "找貨", "集運", "工業品", "五金"],
    deliverables: ["找貨建議", "採購清單", "成本試算", "代訂協助"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000302",
    sku: "PROC-INDUSTRIAL",
    name: "Industrial Goods Sourcing",
    displayName: "工業品找貨 / 採購協助",
    businessUnitCode: "TOOLS_PROCUREMENT",
    type: PRODUCT_TYPE.SERVICE,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依找貨難度、供應商數量、採購金額與文件需求估價。",
    description: "協助尋找工業材料、五金、電子材料、小型設備或替代品。",
    targetCustomers: ["工廠", "採購", "維修單位", "工程師"],
    keywords: ["工業品", "找貨", "採購", "電子材料", "五金", "替代品", "供應商"],
    deliverables: ["供應商比對", "規格確認", "成本分析"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000401",
    sku: "PACK-BOX",
    name: "Reused Carton Box",
    displayName: "再利用紙箱 / 包材",
    businessUnitCode: "PACKAGING_MATERIALS",
    type: PRODUCT_TYPE.MATERIAL,
    pricingModel: PRICING_MODEL.UNIT_PRICE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依尺寸、數量、整理成本與面交/配送方式估價。",
    description: "科技廠、藥局、甜點店等來源之再利用紙箱與包材，主打透明公益提撥。",
    targetCustomers: ["電商賣家", "影印店", "工作室", "小量出貨者"],
    keywords: ["紙箱", "包材", "再利用", "回收", "出貨", "公益", "緩衝材"],
    deliverables: ["紙箱整理", "尺寸分類", "面交或配送"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000402",
    sku: "PACK-FILM",
    name: "Industrial Stretch Film",
    displayName: "工業膠膜 / 棧板膜",
    businessUnitCode: "PACKAGING_MATERIALS",
    type: PRODUCT_TYPE.MATERIAL,
    pricingModel: PRICING_MODEL.UNIT_PRICE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依進貨成本、數量、運費與平台費用估價。",
    description: "工業膠膜、棧板膜、包裝耗材，適合倉儲、搬運與棧板包裝。",
    targetCustomers: ["倉儲", "物流", "工廠", "出貨單位"],
    keywords: ["膠膜", "棧板膜", "包裝膜", "工業膠膜", "包材", "倉儲"],
    deliverables: ["商品供應", "規格確認", "出貨"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000501",
    sku: "COSMO-LS-R902",
    name: "COSMO LS-R902",
    displayName: "COSMO LS-R902 氣密測試設備",
    businessUnitCode: "COSMO_EQUIPMENT",
    type: PRODUCT_TYPE.EQUIPMENT,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "原廠成本 + 代理服務 + 教育訓練 + 保固協調 + 軟體加值。",
    description: "COSMO LS-R902 氣密測試設備，搭配原廠保固、教育訓練與自動記錄數據軟體。",
    targetCustomers: ["水冷產業", "科技廠", "品保部門", "測試站"],
    keywords: ["COSMO", "LS-R902", "氣密", "測漏", "Leak", "水冷", "測試設備"],
    deliverables: ["設備供應", "教育訓練", "保固協調", "數據紀錄軟體"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000502",
    sku: "COSMO-DATA-SW",
    name: "COSMO Data Recording Software",
    displayName: "COSMO 自動記錄數據軟體",
    businessUnitCode: "COSMO_EQUIPMENT",
    type: PRODUCT_TYPE.SOFTWARE,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依欄位、掃碼流程、Excel 模板與防呆需求估價。",
    description: "掃碼按測試，測試完成自動寫入 Excel，具備防呆機制。",
    targetCustomers: ["COSMO 設備客戶", "測試站", "品保單位"],
    keywords: ["COSMO", "Excel", "自動記錄", "掃碼", "數據", "防呆"],
    deliverables: ["流程設計", "軟體設定", "Excel 模板", "測試"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000601",
    sku: "EQP-THERMAL",
    name: "Thermal Test Equipment Agency",
    displayName: "熱特性 / 熱交換測試設備代理",
    businessUnitCode: "EQUIPMENT_AGENCY",
    type: PRODUCT_TYPE.EQUIPMENT,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "原廠成本 + 代理服務 + 技術溝通 + 售後協調。",
    description: "熱交換機、熱特性測試儀、液冷元件測試設備與相關設備代理媒合。",
    targetCustomers: ["水冷產業", "科技廠", "實驗室", "研發單位"],
    keywords: ["熱交換", "熱特性", "液冷", "測試儀", "設備代理", "LW-9670B"],
    deliverables: ["設備規格確認", "原廠溝通", "報價", "導入協助"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000602",
    sku: "EQP-CLEAN-DRY",
    name: "Cleaning Drying Equipment",
    displayName: "清洗烘乾設備代理",
    businessUnitCode: "EQUIPMENT_AGENCY",
    type: PRODUCT_TYPE.EQUIPMENT,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "原廠成本 + 代理服務 + 導入協調。",
    description: "清洗烘乾設備、真空設備、氦檢設備等工業設備代理或媒合。",
    targetCustomers: ["科技廠", "製造業", "清洗製程", "品保單位"],
    keywords: ["清洗", "烘乾", "真空", "氦檢", "設備", "三聯", "均緯"],
    deliverables: ["供應商媒合", "規格確認", "報價協助"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000701",
    sku: "LOG-AIR",
    name: "International Air Freight",
    displayName: "國際空運 / 出口協助",
    businessUnitCode: "LOGISTICS_CUSTOMS",
    type: PRODUCT_TYPE.SERVICE,
    pricingModel: PRICING_MODEL.COST_PLUS,
    currency: "TWD",
    standardPrice: null,
    costBasis: "運費 + 報關費 + 文件處理 + 服務費。",
    description: "國際空運、出口文件、越南物流、CIP 條件與報關協助。",
    targetCustomers: ["出口商", "科技廠", "代購客戶", "跨境電商"],
    keywords: ["空運", "出口", "越南", "報關", "CIP", "物流", "機場"],
    deliverables: ["物流方案", "報價", "文件確認", "出貨追蹤"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000702",
    sku: "LOG-CUSTOMS",
    name: "Customs / Label Support",
    displayName: "報關 / 標籤文件協助",
    businessUnitCode: "LOGISTICS_CUSTOMS",
    type: PRODUCT_TYPE.SERVICE,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依文件數量、危險品規範、標籤語言與審查需求估價。",
    description: "出口標籤、危險品標示、MSDS、IATA、越南文/英文標籤與文件整理。",
    targetCustomers: ["出口商", "化學品供應商", "科技廠"],
    keywords: ["報關", "標籤", "MSDS", "IATA", "UN1133", "危險品", "越南文", "英文"],
    deliverables: ["標籤文字", "文件清單", "規範檢查"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000801",
    sku: "WEB-CORP",
    name: "Corporate Website",
    displayName: "企業形象網站",
    businessUnitCode: "WEBSITE_SYSTEM",
    type: PRODUCT_TYPE.PROJECT,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依頁數、設計複雜度、表單串接、SEO 與後台需求估價。",
    description: "企業形象網站、GitHub Pages、SEO 基礎、表單串接與品牌服務頁。",
    targetCustomers: ["中小企業", "個人品牌", "工作室"],
    keywords: ["網站", "企業形象", "GitHub Pages", "SEO", "表單", "Landing Page"],
    deliverables: ["網站頁面", "RWD", "表單串接", "基礎 SEO"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-000802",
    sku: "SYS-GSHEET",
    name: "Google Sheets Workflow System",
    displayName: "Google Sheets / Apps Script 系統",
    businessUnitCode: "WEBSITE_SYSTEM",
    type: PRODUCT_TYPE.PROJECT,
    pricingModel: PRICING_MODEL.PROJECT_SCOPE,
    currency: "TWD",
    standardPrice: null,
    costBasis: "依表單數量、欄位、通知流程與自動化需求估價。",
    description: "Google 表單、Google Sheets、Apps Script、Gmail 通知、LINE OA 或 Telegram 串接。",
    targetCustomers: ["中小企業", "行政團隊", "業務團隊", "工作室"],
    keywords: ["Google Sheets", "Apps Script", "表單", "Gmail", "LINE OA", "Telegram", "自動化"],
    deliverables: ["表單", "試算表", "Apps Script", "通知流程"],
    status: PRODUCT_STATUS.ACTIVE
  },
  {
    productId: "PRD-999999",
    sku: "OTHER-MANUAL",
    name: "Manual Review Service",
    displayName: "未分類服務 / 人工評估",
    businessUnitCode: "OTHER",
    type: PRODUCT_TYPE.OTHER,
    pricingModel: PRICING_MODEL.MANUAL,
    currency: "TWD",
    standardPrice: null,
    costBasis: "人工評估。",
    description: "無法自動分類或需要人工確認的產品 / 服務。",
    targetCustomers: ["未分類"],
    keywords: [],
    deliverables: ["人工評估"],
    status: PRODUCT_STATUS.ACTIVE
  }
]);
